services:
  # Use Render's official free MongoDB service
  - type: db
    name: mongo
    databaseName: resolveai_db
    plan: free

  # The Backend Server
  - type: web
    name: server
    env: node
    rootDir: ./server
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: mongo
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # The Frontend Client
  - type: static_site
    name: client
    rootDir: ./client
    buildCommand: "npm install && npm run build"
    publishDir: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html